"""PIE Music Engine tools for FL Studio MCP."""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from fastmcp import FastMCP

def register_pie_music_tools(mcp: FastMCP) -> None:
    """Register Music Engine tools with the MCP server."""
    from fl_studio_mcp.pie.music_engine import get_music_engine

    @mcp.tool()
    def music_generate_harmony(chords: list[list[int]], durations: list[float], start_time: float = 0.0, base_velocity: float = 0.8) -> dict[str, Any]:
        """Generate MIDI data for a harmony.

        Args:
            chords: List of chords, where each chord is a list of MIDI note integers (e.g. [[60, 64, 67], [62, 65, 69]]).
            durations: The duration in quarter notes for each chord (must match length of chords).
            start_time: Starting offset.
            base_velocity: Base velocity (0.0 to 1.0).
        """
        me = get_music_engine()
        notes = me.generate_harmony(chords, durations, start_time, base_velocity)
        return {"notes": notes}

    @mcp.tool()
    def music_generate_bass(midi_sequence: list[int], durations: list[float], start_time: float = 0.0, base_velocity: float = 0.9) -> dict[str, Any]:
        """Generate MIDI data for a bassline.

        Args:
            midi_sequence: List of MIDI root notes.
            durations: Duration of each note.
            start_time: Starting offset.
            base_velocity: Velocity (0.0 to 1.0).
        """
        me = get_music_engine()
        notes = me.generate_bass(midi_sequence, durations, start_time, base_velocity)
        return {"notes": notes}

    @mcp.tool()
    def music_humanize_groove(notes: list[dict[str, Any]], timing_variance: float = 0.02, velocity_variance: float = 0.1) -> dict[str, Any]:
        """Apply humanization (swing/micro-timing) to a set of generated notes.

        Args:
            notes: The list of note dicts generated by harmony or bass tools.
            timing_variance: Std. deviation for time noise.
            velocity_variance: Std. deviation for velocity noise.
        """
        me = get_music_engine()
        humanized = me.humanize_timing_and_velocity(notes, timing_variance, velocity_variance)
        return {"notes": humanized}

    @mcp.tool()
    def music_generate_drums(drum_patterns: dict[str, list[bool]]) -> dict[str, Any]:
        """Generate grid bits for a drum pattern.

        Args:
            drum_patterns: Dict mapping channel names to boolean arrays (e.g. {"kick": [True, False, False, False]}).
        """
        me = get_music_engine()
        steps = me.generate_drums(drum_patterns)
        return {"steps": steps}

    @mcp.tool()
    def music_generate_from_external_model(model_type: str, prompt: str, length_beats: float = 16.0) -> dict[str, Any]:
        """Fetch advanced MIDI sequences directly from external AI models (e.g. Magenta/Suno).

        Args:
            model_type: 'melody' or 'drum'
            prompt: Text describing the musical intent (e.g., 'Complex jazz breakbeat')
            length_beats: Target length in quarter notes.
        """
        from fl_studio_mcp.pie.music_llm import get_external_music_connector
        connector = get_external_music_connector()
        return connector.fetch_advanced_midi(model_type, prompt, length_beats)
