"""Install dedicated Piano roll scripts for the Zomboy track directly into FL Studio.
This gives the user 1-click access to inject each pattern right from FL Studio's Piano roll menu.
"""

import os
from fl_studio_mcp.pyscript_gen import PIANO_ROLL_SCRIPTS_DIR

TEMPLATE = '''# Script.Name = "{name}"
# Script.Category = "Zomboy Mind Control"
# Generated by fl-studio-mcp.

import flpianoroll as flp

MODE = 'replace'
NOTES = {notes!r}

def _run():
    score = flp.score
    bar = score.PPQ * 4
    if MODE == "replace":
        try:
            score.clearNotes(True)
        except TypeError:
            score.clearNotes()
    for pitch, t_bars, len_bars, vel in NOTES:
        n = flp.Note()
        n.number = int(pitch)
        n.time = int(round(t_bars * bar))
        n.length = max(1, int(round(len_bars * bar)))
        n.velocity = float(vel)
        score.addNote(n)

def _go():
    undo = getattr(flp.score, "undoSection", None)
    if callable(undo):
        try:
            with undo():
                _run()
            return
        except Exception:
            pass
    _run()

_go()
'''

def install_scripts():
    os.makedirs(PIANO_ROLL_SCRIPTS_DIR, exist_ok=True)

    # 1. Intro Chords
    intro_chords = [
        (53, 0.0, 2.0, 0.70), (56, 0.0, 2.0, 0.65), (60, 0.0, 2.0, 0.65),
        (49, 2.0, 2.0, 0.70), (53, 2.0, 2.0, 0.65), (56, 2.0, 2.0, 0.65),
    ]
    p1 = os.path.join(PIANO_ROLL_SCRIPTS_DIR, "Zomboy_1_Intro_Chords.pyscript")
    with open(p1, "w", encoding="utf-8") as f:
        f.write(TEMPLATE.format(name="1. Intro Chords (Fm - Db)", notes=intro_chords))
    print("Created:", p1)

    # 2. Build Snare Roll
    build_notes = []
    for bar in range(2):
        for beat in range(4):
            t = float(bar + beat * 0.25)
            v = 0.40 + (t / 8.0) * 0.35
            build_notes.append((60, t, 0.15, min(0.95, v)))
    for bar in range(2, 4):
        for eighth in range(8):
            t = float(bar + eighth * 0.125)
            v = 0.45 + (t / 8.0) * 0.40
            build_notes.append((60, t, 0.08, min(0.95, v)))
    for bar in range(4, 6):
        for sixteenth in range(16):
            t = float(bar + sixteenth * 0.0625)
            v = 0.50 + (t / 8.0) * 0.45
            build_notes.append((60, t, 0.04, min(0.98, v)))
    for thirtysecond in range(32):
        t = float(6.0 + thirtysecond * 0.03125)
        build_notes.append((60, t, 0.02, 0.95))
    for thirtysecond in range(24): # Beat 4 cut!
        t = float(7.0 + thirtysecond * 0.03125)
        build_notes.append((60, t, 0.02, 1.0))
    p2 = os.path.join(PIANO_ROLL_SCRIPTS_DIR, "Zomboy_2_Build_Snare_Roll.pyscript")
    with open(p2, "w", encoding="utf-8") as f:
        f.write(TEMPLATE.format(name="2. Build Snare Roll (8 Bars Crescendo)", notes=build_notes))
    print("Created:", p2)

    # 3. Drop Drums (Kick + Snare + Hat)
    # Pitch 60 (standard root)
    drop_kicks = []
    for bar in range(4):
        drop_kicks.append((60, float(bar), 0.2, 1.0))
        if bar % 2 == 1:
            drop_kicks.append((60, float(bar + 0.6875), 0.15, 0.90))
        if bar == 3:
            drop_kicks.append((60, float(bar + 0.875), 0.125, 0.95))
    p3 = os.path.join(PIANO_ROLL_SCRIPTS_DIR, "Zomboy_3_Drop_Kicks.pyscript")
    with open(p3, "w", encoding="utf-8") as f:
        f.write(TEMPLATE.format(name="3. Drop Kicks (Half-time Dubstep)", notes=drop_kicks))
    print("Created:", p3)

    drop_snares = [(60, float(bar + 0.50), 0.25, 1.0) for bar in range(4)]
    p3_snare = os.path.join(PIANO_ROLL_SCRIPTS_DIR, "Zomboy_3_Drop_Snares.pyscript")
    with open(p3_snare, "w", encoding="utf-8") as f:
        f.write(TEMPLATE.format(name="3. Drop Snares (Beat 3 Halftime)", notes=drop_snares))
    print("Created:", p3_snare)

    drop_hats = []
    for bar in range(4):
        for i in range(16):
            t = float(bar + i * 0.0625)
            v = 0.80 if i % 2 == 1 else 0.45
            drop_hats.append((60, t, 0.04, v))
    p3_hat = os.path.join(PIANO_ROLL_SCRIPTS_DIR, "Zomboy_3_Drop_HiHats.pyscript")
    with open(p3_hat, "w", encoding="utf-8") as f:
        f.write(TEMPLATE.format(name="3. Drop Hi-Hats (16th Groove)", notes=drop_hats))
    print("Created:", p3_hat)

    # 4. Drop Growl Bass (27 notes)
    drop_bass = [
        (29, 0.0, 0.20, 1.0), (41, 0.0, 0.20, 1.0), (41, 0.25, 0.125, 0.90),
        (41, 0.375, 0.0625, 0.85), (44, 0.625, 0.125, 0.95), (43, 0.75, 0.125, 0.90),
        (41, 0.875, 0.08, 0.95), (29, 1.0, 0.20, 1.0), (46, 1.125, 0.125, 0.90),
        (44, 1.25, 0.125, 0.85), (41, 1.625, 0.125, 0.90), (41, 1.75, 0.0625, 0.85),
        (41, 1.8125, 0.0625, 0.85), (41, 1.875, 0.08, 0.95), (29, 2.0, 0.20, 1.0),
        (41, 2.0, 0.20, 1.0), (41, 2.25, 0.125, 0.90), (48, 2.625, 0.125, 0.95),
        (46, 2.75, 0.125, 0.90), (44, 2.875, 0.08, 0.95), (29, 3.0, 0.20, 1.0),
        (41, 3.0, 0.20, 1.0), (43, 3.25, 0.125, 0.90), (53, 3.666, 0.08, 1.0),
        (51, 3.75, 0.08, 0.95), (49, 3.833, 0.08, 0.95), (48, 3.916, 0.08, 1.0),
    ]
    p4 = os.path.join(PIANO_ROLL_SCRIPTS_DIR, "Zomboy_4_Drop_Growl_Bass.pyscript")
    with open(p4, "w", encoding="utf-8") as f:
        f.write(TEMPLATE.format(name="4. Drop Growl Bass (27 Notes F Phrygian)", notes=drop_bass))
    print("Created:", p4)

if __name__ == "__main__":
    install_scripts()
